### ISSUE TITLE
Go to definition/Peak definition works only in the same file

### ISSUE THREAD

**Issue by evgygor** [TwitchBronBron/vscode-brightscript-language#40]
Go to definition/Peak definition works only in the same file, so I think the readme should be updated with the info

**Comment by georgejecook** [comment]
I've got a branch in progress which fixes these issues, which will land later this week.

**Comment by georgejecook** [comment]
@TwitchBronBron I think this is resolved, right?

**Comment by evgygor** [comment]
> @TwitchBronBron I think this is resolved, right?

Works very well!
I have several cases that 'go to definition' or  'peek...' does not work.
How can I assists with debug?

**Comment by georgejecook** [comment]
cool. In that case, close this issue (because it does work in the same
file, so this is resolved) and to help us debug, open a new issue with the
details for the specific case. Code snippets will really help.




On December 9, 2018 at 2:14:50 PM, Evgeny Gorelik (notifications@github.com)
wrote:

@TwitchBronBron <https://github.com/TwitchBronBron> I think this is
resolved, right?

Works very well!
I have several cases that 'go to definition' or 'peek...' does not work.
How can I assists with debug?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/TwitchBronBron/vscode-brightscript-language/issues/40#issuecomment-445563231>,
or mute the thread

**Comment by TwitchBronBron** [comment]
Yeah it looks like it's working for me!
