### ISSUE TITLE
check if debugging session is out of sync

### ISSUE THREAD

**Issue by georgejecook** [TwitchBronBron/vscode-brightscript-language#42]
We could feasibly check the line of code from the debugger against the code in the editor and warn the user if they are not the same.

This could help programmer's avoid debugging stale/non-updated deployments or spot problems with their deployment scripts.

use case: I've found quite a few times I _think_ my deploy has worked; but it has not and I've launched a prior version of the app.

Another take on this could be to inject a build guid into a codefile, and code that spits it out on launch..

**Comment by TwitchBronBron** [comment]
What causes the debugging session to get out of sync? Is there a compile error, or perhaps an issue with the zip file bundling? Because in the normal flow, the extension deletes any previous zip file and intermediary source files, makes the zip file from current sources, and then deploys. So I can't think of any way for a deployment to become out of sync....it should always have latest. 

Is it possible that this is actually an issue with your current build process (gulp, make, whatever)?

**Comment by georgejecook** [comment]
thinking about it; this is a very specific use case of mine (testing side-loaded builds with deeplinking; but hijacking the debug session). I'll close it.
