### ISSUE TITLE
Disable Syntax Highlighting

### ISSUE THREAD

**Issue by reidcooper** [TwitchBronBron/vscode-brightscript-language#72]
Request to disable this extension's syntax highlighting, especially if you've created your own.

**Comment by TwitchBronBron** [comment]
Hmm. I don't really know how to do this. We contribute the language grammar [here](https://github.com/TwitchBronBron/vscode-brightscript-language/blob/88d80933349fe14034546a524a13b1a9f369b551/package.json#L265) in the package.json, which is static and used when the extension is generated. I'm not sure if there's a way to programmatically disable the grammar from within the extension. 

However, with that said, there might be a way for you to get around this on your end. I think you can create a vscode extension and declare your own "language" like "MyCustomBrightScript", and then in user settings, tell vscode that anytime it encounters a .brs file, associate it with "MyCustomBrightScript" instead of the "brightscript" language that we contribute. [Here's](https://code.visualstudio.com/docs/languages/overview#_adding-a-file-extension-to-a-language) that vscode setting

**Comment by TwitchBronBron** [comment]
@reidcooper If you know of a way to programmatically do what you're asking, I'm more than happy to add that as a setting.

**Comment by TwitchBronBron** [comment]
@reidcooper I'm closing this issue for now. I'm willing to re-open if you have any suggestions on how this would actually be implemented.
